name: Test
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  benchmark:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - CairoMakie
          - GLMakie
          - WGLMakie
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          include-all-prereleases: false
          arch: x64
      - uses: julia-actions/cache@v2
      - name: Testing        
        env:
          GITHUB_TOKEN: ${{ secrets.BENCHMARK_KEY }}
          PR_NUMBER: ${{ github.event.number }}
        run: >
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=. -e 'using Pkg; Pkg.test(coverage = true)'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: COMODO-research/Comodo.jl
